In [ ]:
import pandas as pd 
import os  

# função de cadastro
def cadastrar_novo():
    nome = input("Nome do funcionário: ").strip().title()
    cargo = input("Cargo: ").strip().capitalize()
    
    while cargo.isnumeric():
        cargo = input("Cargo inválido. Digite novamente: ").strip().title()
    salario = input("Salário: ").replace(".", "").replace(",", ".").strip()

    while True:
        try:
            salario = float(salario)
            break
        except ValueError:
            salario = input("Salário inválido. Digite novamente: ").replace(".", "").replace(",", ".").strip()

    cidade = input("Cidade: ").strip().title()
    
    while cidade.isnumeric():
        cidade = input("Cidade inválida. Digite novamente: ").strip().title()
    estado = input("Estado: ").strip().upper()
    
    while estado.isnumeric():
        estado = input("Estado inválido. Digite novamente: ").strip().upper()

    funcionario = {
        "NOME": nome,
        "CARGO": cargo,
        "SALARIO": salario,
        "CIDADE": cidade,
        "ESTADO": estado
    }
    return funcionario

# função para alteração
def alterar_funcionario(df):
    nome = input("Digite o nome do funcionário que deseja alterar: ").title()
    # verificar se funcionário existe
    if nome not in df['NOME'].values:
        print("Funcionário não encontrado.")
        return df
    # mostrar dados atuais
    print("\nDados atuais:")
    print(df[df['NOME'] == nome])
    campo = input("\nQual campo deseja alterar? (CARGO / SALARIO / CIDADE / ESTADO): ").upper().strip()
    if campo not in df.columns:
        print("Campo inválido.")
    novo_valor = input(f"Digite o novo valor para {campo}: ").strip().title()
    # tratar salário
    if campo == "SALARIO":
        novo_valor = novo_valor.replace(".", "").replace(",", ".")
        try:
            novo_valor = float(novo_valor)
        except ValueError:
            print("Valor de salário inválido.")
            
    # atualizar valor
    df.loc[df['NOME'] == nome, campo] = novo_valor
    print("\nRegistro atualizado:")
    print(df[df['NOME'] == nome])
    return df

# função de exclusão
def excluir_funcionario(df):
    nome = input("Digite o nome do funcionário que deseja excluir: ").strip().title()
    # verificar se funcionário existe
    if nome not in df['NOME'].values:
        print("Funcionário não encontrado.")
        
    df = df[df['NOME'] != nome]
    print("\nRegistro excluído:")
    print(df[df['NOME'] == nome])
    return df

# função de busca
def buscar_funcionario(df):
    nome = input("Digite o nome do funcionário que deseja buscar: ").strip().title()
    # verificar se funcionário existe
    if nome not in df['NOME'].values:
        print("Funcionário não encontrado.")
        return df
    print("\nDados do funcionário:")
    print(df[df['NOME'] == nome])

In [ ]:
# modulo de cadastro
import pandas as pd  

cadastro = []

arquivo = "cadastro_func.csv"

# verificar se arquivo existe
if os.path.exists(arquivo):
    dflido = pd.read_csv(arquivo)
else:
    dflido = pd.DataFrame()

while True:

    opcao = input("Digite 'novo' para cadastrar ou 'parar' para sair: ").lower().strip()

    if opcao == "parar":
        break

    if opcao == "novo":
        # chama a função criada
        funcionario = cadastrar_novo()
        cadastro.append(funcionario)

# novos cadastros
dfcadastro = pd.DataFrame(cadastro)

# juntar dados antigos + novos empilhando
df_final = pd.concat([dflido, dfcadastro], ignore_index=True)

# salvar arquivo atualizado, usando o mesmo nome
df_final.to_csv(arquivo, index=False)

display(df_final)

                NOME        CARGO   SALARIO   CIDADE ESTADO
0           Fernanda      Gerente   8698.34    Bauru     SP
1              Andre  Analista jr   4567.23    Bauru     SP
2            Marilda      Gerente  12567.51    Bauru     SP
3         Joao Paulo   Assistente   4000.00    Bauru     SP
4              Neuza      Gerente  10345.72  Arealva     SP
5        Joao Manoel      Gerente  12348.89    Bauru     SP
6              Mayra      Gerente   8765.76  Arealva     SP
7  Fernanda Justulin      Gerente   6700.00  Arealva     SP

In [5]:
# modulo alteração
import pandas as pd  

arquivo = "cadastro_func.csv"
df_final = pd.read_csv(arquivo)

display(df_final)

alterar_valores = input("Deseja alterar valores, digite 'sim' para alterar:").strip().lower()

if alterar_valores == 'sim':
    # chama a função criada
    df_final = alterar_funcionario(df_final)

else:
    print("Programa encerrado")

# salvar alterações
df_final.to_csv(arquivo, index=False)

display(df_final)

                NOME        CARGO   SALARIO   CIDADE ESTADO
0           Fernanda      Gerente   8698.34    Bauru     SP
1              Andre  Analista jr   4567.23    Bauru     SP
2            Marilda      Gerente  12567.51    Bauru     SP
3         Joao Paulo   Assistente   4000.00    Bauru     SP
4              Neuza      Gerente  10345.72  Arealva     SP
5        Joao Manoel      Gerente  12348.89    Bauru     SP
6              Mayra      Gerente   8765.76  Arealva     SP
7  Fernanda Justulin      Gerente   6700.00  Arealva     SP

Dados atuais:
                NOME    CARGO  SALARIO   CIDADE ESTADO
7  Fernanda Justulin  Gerente   6700.0  Arealva     SP

Registro atualizado:
                NOME    CARGO  SALARIO CIDADE ESTADO
7  Fernanda Justulin  Gerente   6700.0  Bauru     SP

                NOME        CARGO   SALARIO   CIDADE ESTADO
0           Fernanda      Gerente   8698.34    Bauru     SP
1              Andre  Analista jr   4567.23    Bauru     SP
2            Marilda      Gerente  12567.51    Bauru     SP
3         Joao Paulo   Assistente   4000.00    Bauru     SP
4              Neuza      Gerente  10345.72  Arealva     SP
5        Joao Manoel      Gerente  12348.89    Bauru     SP
6              Mayra      Gerente   8765.76  Arealva     SP
7  Fernanda Justulin      Gerente   6700.00    Bauru     SP

In [ ]:
# modulo exclusão
import pandas as pd  

df_final = pd.read_csv('cadastro_func.csv')

display(df_final)

excluir_valores = input("Deseja excluir valores, digite 'sim' para alterar:").strip().lower()

if excluir_valores == 'sim':
    # chama a função criada
    df_final = excluir_funcionario(df_final)

else:
    print("Programa encerrado")

# salvar alterações
df_final.to_csv("cadastro_func.csv", index=False)

display(df_final)

          NOME          CARGO   SALARIO CIDADE ESTADO
0        Andre    Analista jr   8690.87  Bauru     SP
1     Fernanda       Auxiliar   1500.97  Bauru     SP
2         Joao  Assistente Jr   7548.87  Bauru     SP
3      Marilda        Gerente  12450.97  Bauru     SP
4  Joao Manoel        Diretor  12340.56  Bauru     SP

Registro excluído:
Empty DataFrame
Columns: [NOME, CARGO, SALARIO, CIDADE, ESTADO]
Index: []

          NOME        CARGO   SALARIO CIDADE ESTADO
0        Andre  Analista jr   8690.87  Bauru     SP
1     Fernanda     Auxiliar   1500.97  Bauru     SP
3      Marilda      Gerente  12450.97  Bauru     SP
4  Joao Manoel      Diretor  12340.56  Bauru     SP

In [7]:
# modulo busca funcionário
import pandas as pd  

arquivo = 'cadastro_func.csv'

df_final = pd.read_csv(arquivo)

display(df_final)

buscar_funcionario(df_final)

                NOME        CARGO   SALARIO   CIDADE ESTADO
0           Fernanda      Gerente   8698.34    Bauru     SP
1              Andre  Analista jr   4567.23    Bauru     SP
2            Marilda      Gerente  12567.51    Bauru     SP
3         Joao Paulo   Assistente   4000.00    Bauru     SP
4              Neuza      Gerente  10345.72  Arealva     SP
5        Joao Manoel      Gerente  12348.89    Bauru     SP
6              Mayra      Gerente   8765.76  Arealva     SP
7  Fernanda Justulin      Gerente   6700.00    Bauru     SP

Dados do funcionário:
                NOME    CARGO  SALARIO CIDADE ESTADO
7  Fernanda Justulin  Gerente   6700.0  Bauru     SP